

export const listCategory = (t:any) => [
  { value: "nursing_care", label: t("category.nursing_care") },
  { value: "building_cleaning", label: t("category.building_cleaning") },
  { value: "manufacturing", label: t("category.manufacturing") },
  { value: "construction", label: t("category.construction") },
  { value: "shipbuilding_marine", label: t("category.shipbuilding_marine") },
  { value: "automobile_repair", label: t("category.automobile_repair") },
  { value: "aviation", label: t("category.aviation") },
  { value: "hospitality", label: t("category.hospitality") },
  { value: "agriculture", label: t("category.agriculture") },
  { value: "fishery", label: t("category.fishery") },
  { value: "food_manufacturing", label: t("category.food_manufacturing") },
  { value: "food_service", label: t("category.food_service") },
  { value: "industrial_waste", label: t("category.industrial_waste") },
  { value: "railway", label: t("category.railway") },
  { value: "automobile_transport", label: t("category.automobile_transport") },
  { value: "forestry", label: t("category.forestry") },
  { value: "wood_industry", label: t("category.wood_industry") },
  { value: "others", label: t("category.other") },
];

export const regionList = (t:any) => [
  { value: "hokkaido", label: t("region.hokkaido") },
  { value: "aomori", label: t("region.aomori") },
  { value: "iwate", label: t("region.iwate") },
  { value: "miyagi", label: t("region.miyagi") },
  { value: "akita", label: t("region.akita") },
  { value: "yamagata", label: t("region.yamagata") },
  { value: "fukushima", label: t("region.fukushima") },
  { value: "ibaraki", label: t("region.ibaraki") },
  { value: "tochigi", label: t("region.tochigi") },
  { value: "gunma", label: t("region.gunma") },
  { value: "saitama", label: t("region.saitama") },
  { value: "chiba", label: t("region.chiba") },
  { value: "tokyo", label: t("region.tokyo") },
  { value: "kanagawa", label: t("region.kanagawa") },
  { value: "niigata", label: t("region.niigata") },
  { value: "toyama", label: t("region.toyama") },
  { value: "ishikawa", label: t("region.ishikawa") },
  { value: "fukui", label: t("region.fukui") },
  { value: "yamanashi", label: t("region.yamanashi") },
  { value: "nagano", label: t("region.nagano") },
  { value: "gifu", label: t("region.gifu") },
  { value: "shizuoka", label: t("region.shizuoka") },
  { value: "aichi", label: t("region.aichi") },
  { value: "mie", label: t("region.mie") },
  { value: "shiga", label: t("region.shiga") },
  { value: "kyoto", label: t("region.kyoto") },
  { value: "osaka", label: t("region.osaka") },
  { value: "hyogo", label: t("region.hyogo") },
  { value: "nara", label: t("region.nara") },
  { value: "wakayama", label: t("region.wakayama") },
  { value: "tottori", label: t("region.tottori") },
  { value: "shimane", label: t("region.shimane") },
  { value: "okayama", label: t("region.okayama") },
  { value: "hiroshima", label: t("region.hiroshima") },
  { value: "yamaguchi", label: t("region.yamaguchi") },
  { value: "tokushima", label: t("region.tokushima") },
  { value: "kagawa", label: t("region.kagawa") },
  { value: "ehime", label: t("region.ehime") },
  { value: "kochi", label: t("region.kochi") },
  { value: "fukuoka", label: t("region.fukuoka") },
  { value: "saga", label: t("region.saga") },
  { value: "nagasaki", label: t("region.nagasaki") },
  { value: "kumamoto", label: t("region.kumamoto") },
  { value: "oita", label: t("region.oita") },
  { value: "miyazaki", label: t("region.miyazaki") },
  { value: "kagoshima", label: t("region.kagoshima") },
  { value: "okinawa", label: t("region.okinawa") },
];

