export const listCategory = [
  { value: "nursing_care", label: "Nursing care" },
  { value: "building_cleaning", label: "Building cleaning" },
  { value: "manufacturing", label: "Manufacturing (materials/machinery/electronics)" },
  { value: "construction", label: "Construction" },
  { value: "shipbuilding_marine", label: "Shipbuilding & marine" },
  { value: "automobile_repair", label: "Automobile repair & maintenance" },
  { value: "aviation", label: "Aviation" },
  { value: "hospitality", label: "Lodging / Hospitality" },
  { value: "agriculture", label: "Agriculture" },
  { value: "fishery", label: "Fishery" },
  { value: "food_manufacturing", label: "Food & beverage manufacturing" },
  { value: "food_service", label: "Food service industry" },
  { value: "industrial_waste", label: "Industrial waste management" },
  { value: "railway", label: "Railway" },
  { value: "automobile_transport", label: "Automobile transport" },
  { value: "forestry", label: "Forestry" },
  { value: "wood_industry", label: "Wood industry" },
];

export const regionList = [
  { value: "hokkaido", label: "Hokkaido" },
  { value: "aomori", label: "Aomori" },
  { value: "iwate", label: "Iwate" },
  { value: "miyagi", label: "Miyagi" },
  { value: "akita", label: "Akita" },
  { value: "yamagata", label: "Yamagata" },
  { value: "fukushima", label: "Fukushima" },
  { value: "ibaraki", label: "Ibaraki" },
  { value: "tochigi", label: "Tochigi" },
  { value: "gunma", label: "Gunma" },
  { value: "saitama", label: "Saitama" },
  { value: "chiba", label: "Chiba" },
  { value: "tokyo", label: "Tokyo" },
  { value: "kanagawa", label: "Kanagawa" },
  { value: "niigata", label: "Niigata" },
  { value: "toyama", label: "Toyama" },
  { value: "ishikawa", label: "Ishikawa" },
  { value: "fukui", label: "Fukui" },
  { value: "yamanashi", label: "Yamanashi" },
  { value: "nagano", label: "Nagano" },
  { value: "gifu", label: "Gifu" },
  { value: "shizuoka", label: "Shizuoka" },
  { value: "aichi", label: "Aichi" },
  { value: "mie", label: "Mie" },
  { value: "shiga", label: "Shiga" },
  { value: "kyoto", label: "Kyoto" },
  { value: "osaka", label: "Osaka" },
  { value: "hyogo", label: "Hyogo" },
  { value: "nara", label: "Nara" },
  { value: "wakayama", label: "Wakayama" },
  { value: "tottori", label: "Tottori" },
  { value: "shimane", label: "Shimane" },
  { value: "okayama", label: "Okayama" },
  { value: "hiroshima", label: "Hiroshima" },
  { value: "yamaguchi", label: "Yamaguchi" },
  { value: "tokushima", label: "Tokushima" },
  { value: "kagawa", label: "Kagawa" },
  { value: "ehime", label: "Ehime" },
  { value: "kochi", label: "Kochi" },
  { value: "fukuoka", label: "Fukuoka" },
  { value: "saga", label: "Saga" },
  { value: "nagasaki", label: "Nagasaki" },
  { value: "kumamoto", label: "Kumamoto" },
  { value: "oita", label: "Oita" },
  { value: "miyazaki", label: "Miyazaki" },
  { value: "kagoshima", label: "Kagoshima" },
  { value: "okinawa", label: "Okinawa" },
];

